# Site settings
title:        "Eyowo: Wall of Love"
url:          'http://softcom.ng'
charset:      'UTF-8'
timezone:     Africa/Lagos
typekit_id:   sbm5njs
google_analytics_id: 'UA-122859875-1'

# Build settings
markdown: kramdown

# Collections
collections:
  uploads:
    title:  Uploads (Media & Files)
    output: true
  post-facebook:
    title:  Facebook Testimonies
  post-instagram:
    title:  Instagram Testimonies
  post-twitter:
    title:  Twitter Testimonies
  
# Defaults
defaults:
  - scope:
      type: post-facebook
    values:
      master: true
  - scope:
      type: post-twitter
    values:
      master: true
  - scope:
      type: post-instagram
    values:
      master: true

# Include folders
include:
  - _pages

# Gems
plugins:
  - jekyll/tagging
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  paginate_path: "/page:num/"

# Handling Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - dev
  - .gitignore